name       : libspatialite
version    : 4.3.0a
release    : 5
source     :
    - https://www.gaia-gis.it/gaia-sins/libspatialite-sources/libspatialite-4.3.0a.tar.gz : 88900030a4762904a7880273f292e5e8ca6b15b7c6c3fb88ffa9e67ee8a5a499
license    : MPL-1.1
component  : programming.library
summary    : A library extending the basic SQLite core in order to get a full fledged Spatial DBMS
description: |
    libspatialite - a library extending the basic SQLite core in order to get a full fledged Spatial DBMS
builddeps  :
    - pkgconfig(libxml-2.0)
    - pkgconfig(proj)
    - pkgconfig(sqlite3)
    - geos
environment: |
    export CFLAGS="$CFLAGS -DACCEPT_USE_OF_DEPRECATED_PROJ_API_H=1"
setup      : |
    %configure --disable-static --disable-freexl
build      : |
    %make
install    : |
    %make_install
