name       : libspatialite
version    : 5.0.1
release    : 7
source     :
    - https://www.gaia-gis.it/gaia-sins/libspatialite-sources/libspatialite-5.0.1.tar.gz : eecbc94311c78012d059ebc0fae86ea5ef6eecb13303e6e82b3753c1b3409e98
license    : MPL-1.1
component  : programming.library
summary    : A library extending the basic SQLite core in order to get a full fledged Spatial DBMS
description: |
    libspatialite - a library extending the basic SQLite core in order to get a full fledged Spatial DBMS
builddeps  :
    - pkgconfig(libxml-2.0)
    - pkgconfig(minizip)
    - pkgconfig(proj)
    - pkgconfig(rttopo)
    - pkgconfig(sqlite3)
    - geos
setup      : |
    %configure --disable-static --disable-freexl
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
